# Generated by Django 3.1.5 on 2021-01-07 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20210107_2103'),
        ('Note_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=20)),
                ('note_text', models.TextField()),
                ('is_archive', models.BooleanField(default=False)),
                ('is_pin', models.BooleanField(default=False)),
                ('is_trash', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.userdetails')),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
