# Generated by Django 3.0.5 on 2021-01-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='reminder',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
