# Generated by Django 3.0.5 on 2021-01-09 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note_App', '0003_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.timezone),
        ),
        migrations.AddField(
            model_name='notes',
            name='label',
            field=models.ManyToManyField(blank=True, to='Note_App.Label'),
        ),
    ]
