# Generated by Django 3.0.5 on 2021-01-09 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note_App', '0004_auto_20210109_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 9, 9, 35, 16, 976519)),
        ),
    ]
