# Generated by Django 3.0.5 on 2021-01-09 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Note_App', '0005_auto_20210109_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='date',
        ),
    ]
