# Generated by Django 3.0.5 on 2021-01-09 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Note_App', '0006_remove_notes_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
