# Generated by Django 3.0.5 on 2021-01-09 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Note_App', '0008_auto_20210109_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='labelname',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='date',
        ),
    ]
